### ISSUE TITLE
rickroll page

### ISSUE THREAD

**Issue by alexsquibbs** [erisly/moe#5]
as we all know, everyone loves a great laugh as theyve been rickrolled. just choose a directory that no one will suspect its a rickroll, and put in basically just an autostarting video.

what iv basically done before is literally just the contents of https://snowsgiving.co/index.html, which literally just redirects to https://snowsgiving.co/index.mp4

idk if u will rly like this idea depending on if u like rickrolling people or not, but i think itd be a little funny thing that this site can include. but remember, try disguising it in a directory no one will suspect being a rickroll, and maybe delete this issue after completion so that no one sees this idea.

**Comment by PikaDude** [comment]
I wouldn't mind such a feature tbh. Not sure if I'd add it myself though

**Comment by alexsquibbs** [comment]
> I wouldn't mind such a feature tbh. Not sure if I'd add it myself though

not sure if ud add it urself as "u can make the page if u want it" or "nah, we rly dont need such a thing"?

**Comment by PikaDude** [comment]
you can make the page if you want to lol

**Comment by alexsquibbs** [comment]
> you can make the page if you want to lol

would u rather have the mp4 file hosted off another webserver to save space?

**Comment by PikaDude** [comment]
it's probably best if we host it in the repo but we might want to consider using Git LFS on the repo before doing so

**Comment by alexsquibbs** [comment]
> it's probably best if we host it in the repo but we might want to consider using Git LFS on the repo before doing so

ig i can just use the file hosted on firebase rn just for a temporary solve?

**Comment by PikaDude** [comment]
¯\_(ツ)_/¯

**Comment by alexsquibbs** [comment]
> ¯\_(ツ)_/¯

aight ill just try to figure out something and stop bothering u
